version: '3.8'
services:
  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./code:/code
      - ./nginx/laravel.conf:/etc/nginx/conf.d/laravel.conf
    depends_on:
      - php
      - db
  php:
    image: php:8.1-fpm
    volumes:
      - ./code:/code
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: proforientation
      MYSQL_USER: profadmin
      MYSQL_PASSWORD: Aa123456
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db_data:/var/lib/mysql
  node:
    image: node:21.7.1
    volumes:
      - .:/code
    working_dir: /code
    command: bash -c "npm install && npm run build"
volumes:
  db_data:
