version: '3.8'
services:
  web:
    build:
      context: ./docker/nginx
    ports:
      - "8876:80"
    volumes:
      - ./www:/var/www
    depends_on:
      - php
      - db
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./www:/var/www
    command: sh -c "composer install --no-interaction && php artisan key:generate && php-fpm"
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "${DB_PORT}:3306"
  node:
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    volumes:
      - ./www:/var/www
    working_dir: /var/www
    command: bash -c "npm install && npm run build"
volumes:
  db_data:
