services:
  web:
    build:
      context: ./docker/nginx
    ports:
      - "80:80"
      - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
    volumes:
      - ./www:/var/www
    depends_on:
      - php
      - db
    container_name: project_nginx
  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - ./www:/var/www
    command: sh -c "composer install --no-interaction && php artisan key:generate && php-fpm"
    container_name: project_app
    depends_on:
      - db
  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - ./www/tmp/db:/var/lib/mysql
    ports:
      - 3308:3306
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    container_name: project_db
  node:
    build:
      context: .
      dockerfile: docker/node/Dockerfile
    volumes:
      - ./www:/var/www
    working_dir: /var/www
    container_name: project_node
    command: "npm run dev"
    depends_on:
      - php
volumes:
  db_data:
